=== khoeflm/SemNotam_WebApp/XSD/Segment_XSD/FIRSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="http://semnotam.frequentis.com/schema/1.0"
  xmlns:gml="http://www.opengis.net/gml/3.2"
  xmlns:aixm="http://www.aixm.aero/schema/5.1"  
  xmlns:tns="http://semnotam.frequentis.com/schema/1.0"
  elementFormDefault="qualified">
    
<!--  <import namespace="http://www.opengis.net/gml/3.2" 
    schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd" /> -->
  <import namespace="http://www.aixm.aero/schema/5.1" 
    schemaLocation="../AIXM_Features.xsd"/>
    
  <include schemaLocation="../Query_XSD/QuerySchema.xsd" />  
  
  <element name="FirCollection">
    <complexType>
      <sequence>
        <element name="hasMember" maxOccurs="unbounded" minOccurs="0">
          <complexType>
            <choice>
              <element name="Fir" type="tns:FirType" />
            </choice>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
  
  <complexType name="FirType">
    <sequence>
      <element name="designator" type="token" />
      <element name="localId" type="token" minOccurs="0" />
    </sequence>
    <attribute name="id" type="token" use="required" />
  </complexType>
  
</schema>

=== khoeflm/SemNotam_WebApp/XSD/Segment_XSD/FIRSample.xml
<?xml version="1.0" encoding="UTF-8"?>
<FirCollection xmlns="http://semnotam.frequentis.com/schema/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xsi:schemaLocation="http://semnotam.frequentis.com/schema/1.0 ./FIRSchema.xsd" >
  
  <hasMember>
    <Fir id="KZDC">
      <designator>KZDC</designator>
	  <localId>ZDC</localId>
    </Fir>
  </hasMember>	
  <hasMember>
    <Fir id="KZNY">
	  <designator>KZNY</designator>
      <localId>ZNY</localId>
    </Fir>
  </hasMember>
  <hasMember>
    <Fir id="KZBW">
      <designator>KZBW</designator>	
      <localId>ZBW</localId>
    </Fir>
  </hasMember>
</FirCollection>
